<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_uploaded</name>
   <tag></tag>
   <elementGuidId>faba8967-afca-4d99-b5ad-bcac8a12dc3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postMessageText_6g89c38yzffg7fhai997rbif6w > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;post-list__dynamic&quot;]//div[@style=&quot;position: relative;&quot;][last()]//div[@data-testid=&quot;fileAttachmentList&quot;]//div[@class=&quot;post-image__column&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postMessageText_6g89c38yzffg7fhai997rbif6w&quot;)/p[1]</value>
   </webElementProperties>
</WebElementEntity>
