<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_upload</name>
   <tag></tag>
   <elementGuidId>44e40eb4-30c6-4c71-b86b-955981936e41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postMessageText_6g89c38yzffg7fhai997rbif6w > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;fileUploadInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postMessageText_6g89c38yzffg7fhai997rbif6w&quot;)/p[1]</value>
   </webElementProperties>
</WebElementEntity>
