<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saved_tag</name>
   <tag></tag>
   <elementGuidId>30fe8603-7d99-481d-9ffe-916ab3323936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postMessageText_6g89c38yzffg7fhai997rbif6w > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;post-list__dynamic&quot;]//div[@style=&quot;position: relative;&quot;][last()]//span[text()='Saved']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postMessageText_6g89c38yzffg7fhai997rbif6w&quot;)/p[1]</value>
   </webElementProperties>
</WebElementEntity>
